pref("webmail.server.port.pop", 110);
pref("webmail.server.port.imap", 143);
pref("webmail.server.port.smtp", 25);
pref("webmail.logging.comms.UseLog", false);
pref("webmail.logging.comms.UseJSconsole", false);
pref("webmail.logging.comms.UseFile", true);
pref("webmail.logging.comms.FileLocation", "");
pref("webmail.UseAccountWizard", true);
pref("webmail.bUsePOPServer", true);
pref("webmail.bUseSMTPServer", true);
pref("webmail.bUseIMAPServer", false);
pref("webmail.server.statusbar", false);
pref("webmail.UserAgent", "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.3) Gecko/20071025 Firefox/2.0.0.9");
pref("extensions.{3c8e8390-2cf6-11d9-9669-0800200c9a66}.description", "chrome://web-mail/locale/Webmail.properties");