pref("extensions.{d7103710-6112-11d9-9669-0800200c9a66}.description", "chrome://yahoo/locale/Yahoo.properties");
pref("yahoo.bReUseSession", true);
pref("yahoo.iAccountNum", 0);
pref("yahoo.bUseJunkMail", false);
pref("yahoo.bDownloadUnread", false);
pref("yahoo.bSaveCopy", false);
pref("yahoo.iProcessAmount", 25);
pref("yahoo.iProcessDelay", 10);
pref("yahoo.bUseShortID", false);
