#include "nsISupports.idl"

[scriptable, uuid(e2029f20-3851-11da-8cd6-0800200c9a66)]
interface nsIComponentData : nsISupports
{
    boolean addElement(in string szName, in string szValue);
                            
    string findElement(in string szName);
    
    boolean deleteElement(in string szName);
    
    boolean deleteAllElements();
};
