#include "nsISupports.idl"

[scriptable, uuid(76f4dcb0-284a-11d9-9669-0800200c9a66)]
interface nsIDomainManager : nsISupports
{  
    //1 = database can be accessed
    //0 = database not ready
    boolean isReady();
    
    //returns
    // -1 = db not ready
    // 0 = error
    // 1 = ok
    
    //gets domainhandler id for give domain
    long getDomain(in string Address , out string contentID );
    
    //adds new doamin                  
    long newDomain(in string Address, in string contentID);
     
    //removes given domain                 
    long removeDomain(in string szAddrees);
    
    //gets all domains 
    long getAllDomains(out PRUint32 count,
                       [array, size_is(count)] out string Domains);
};
