#include "nsISupports.idl"
#include "mozIStorageStatementWrapper.idl"

[scriptable, uuid(75874110-09e5-11da-8cd6-0800200c9a66)]
interface nsIDataBaseManager : nsISupports
{  
    mozIStorageStatementWrapper createDBQuery (in string sqlCommand);
};
