#include "nsISupports.idl"
#include "nsISessionData.idl"

[scriptable, uuid(ea67f980-3851-11da-8cd6-0800200c9a66)]
interface nsISessionManager : nsISupports
{
    boolean setSessionData(in nsISessionData sessionData);
    
    boolean removeSession( in string szUserName);
    
    nsISessionData findSessionData(in string szUserName);
};
