#include "nsISupports.idl"
#include "nsIURL.idl"

[scriptable, uuid(4347761c-f729-11db-8314-0800200c9a66)]
interface nsIWebMailCookieManager2 : nsISupports
{
    boolean addCookie(in string szUserName, in nsIURL url, in string szCookie);

    string findCookie(in string szUserName, in nsIURL url);

    boolean removeCookie(in string szUserName);
};
